on: push

jobs:
  unit-test-lint:
    runs-on: ubuntu-latest
    container: python:3.10.10-slim
    
    steps:
      - name: Check out repository code
        uses: actions/checkout@v2
      
      - name: Install requirements
        run: python -m pip install -r requirements.txt
      
      - name: Unit test
        run: python -m pytest .
      
      - name: Lint with flake8
        run: python -m flake8 .
